Apparently Adobe Reader throws the error
RaiseError: Expected a name object.
In other words: if you have Options [(A) (B)]
Adobe Reader expects /V /0 instead of /V (A)